### ISSUE TITLE
Upgrade Plotly Version for 'texttemplate' and Other Features

### ISSUE THREAD

**Issue by Gamma169** [EmberMN/ember-cli-plotly#176]
Hello!  I notice that this package is running a slightly older version of plotly.  Version 1.49.5
https://github.com/EmberMN/ember-cli-plotly/blob/master/package.json#L40

As of this issue, plotly is on version 1.57.1

I notice there is a pull request open that is upgrading plotly to the correct version.
https://github.com/EmberMN/ember-cli-plotly/pull/153

I am trying to use the `texttemplate` functionality implemented in plotly 1.50.0 (the release DIRECTLY after the 1.49.5 release that this package is currently using).  I'm hoping that you can merge the plotly upgrade PR so that we can use the latest version of plotly instead of running off a commit.

**Comment by jacobq** [comment]
O hai :octocat: 
Thanks for the reminder. I haven't been paying much attention to this repository for a while, and it could use some freshening up for sure. I just ran `ember-cli-update`, [`ncu -u`](https://www.npmjs.com/package/npm-check-updates), `yarn`, and `yarn upgrade` over on PR #177.  If its builds OK I'll release as v0.6.0 (wonderful thing about v0.x is that it can go :boom: right? ;))

**Comment by Gamma169** [comment]
I am part of a team managing a production application with clients paying big bucks for a platform heavily reliant on plotly graphs and this library to a degree, ha ha.  We've mostly been using the basic graph functionality, but now we want some more fancy stuff, so we ran into the issue.

Thanks for responding so quickly!  I'll also take a look and see if I can help as well.  I saw your PR, and maybe I can help with the travis issues too. Otherwise, your plan seems good to me. :)

**Comment by jacobq** [comment]
My mass-update commit evidently broke a few things. I'll try to make some time yet this week to fix it up and release, but if you have time feel free to chime in regarding how to resolve the problems that showed up in CI like this one: https://travis-ci.org/github/EmberMN/ember-cli-plotly/jobs/741976878#L284-L311 (looks like somehow some node stuff is getting pulled into the final output, which obviously won't work when targeting a browser)

**Comment by Gamma169** [comment]
Hi.  Sorry for not looking into this yet.  Busy week.  I'll see if I can get someone on my team to help look at this. tomorrow/early next week. :)

**Comment by jacobq** [comment]
@Gamma169 @lsmun I [released](https://www.npmjs.com/package/ember-cli-plotly/v/0.6.0) [v0.6.0](https://github.com/EmberMN/ember-cli-plotly/tree/v0.6.0). Please give it a try and let me know if you run into anything. Also, if you'd like to take a shot at updating this to match Octane conventions or eliminating the observers or even just going through some of the deprecations I would appreciate that very much. (Of course, if you're too busy with other projects I totally get it.)
